# Generated by Django 4.0.6 on 2022-07-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('content_html', models.CharField(max_length=256)),
                ('summary', models.CharField(max_length=256)),
                ('photo', models.CharField(max_length=256)),
                ('date_published', models.CharField(max_length=256)),
            ],
        ),
    ]
